#!/bin/bash
#SBATCH --time=1:00:00
#SBATCH --nodes=1 
#SBATCH --ntasks-per-node=4
#SBATCH --job-name=test_wannier90
#SBATCH --mail-type=END
#SBATCH --account=mleuenberger
#SBATCH --mail-user=d.g.skachkov@gmail.com
#SBATCH --error=error.txt
#SBATCH --output=output.txt

export MV2_ENABLE_AFFINITY=0 
export I_MPI_PIN_DOMAIN=auto 
export I_MPI_PIN_ORDER=bunch 
export KMP_AFFINITY=compact,granularity=fine,1 
export OMP_NUM_THREADS=1

PPN=$(( $SLURM_TASKS_PER_NODE / $OMP_NUM_THREADS ))
echo "PPN = $PPN"

### Quantum Espresso:
module load espresso/espresso-6.6-mvapich2-2.3.1-ic-2019.3.199
mpirun -np $PPN pw.x -ni 1 -nk 1 -nt 1 -nd 1 -nb 1 -input scf.in > scf.out
module unload espresso

### Wannier90 preprocessing
module load wannier90/wannier90-3.1.0-oneapi-2021.2.0
mpirun   -np $PPN  wannier90.x -pp d  
module unload wannier

### Quantum Espresso transform to Wannier90
module load espresso/espresso-6.6-mvapich2-2.3.1-ic-2019.3.199
mpirun   -np $PPN  pw2wannier90.x -in pw2wan.in > pw2wan.out 
module unload espresso

### Wannier90 wannierization
module load wannier90/wannier90-3.1.0-oneapi-2021.2.0
mpirun   -np $PPN  wannier90.x d
module unload wannier

### Quantum Espresso check wannierization
module load espresso/espresso-6.6-mvapich2-2.3.1-ic-2019.3.199
mpirun -np $PPN pw.x -ni 1 -nk 1 -nt 1 -nd 1 -nb 1 -input bands.in > bands.out
mpirun -np $PPN bands.x  -input bandsx.in > bandsx.out



 




